### ISSUE TITLE
Font issue on M1 Mac Big Sur

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level3#105]
See https://github.com/nus-cs2103-AY2122S1/forum/issues/66

**Comment by damithc** [comment]
@se-edu/tech-team-level1 can investigate this one, especially if you are a Mac user?

**Comment by RuiFengg** [comment]
I'm using mac but intel chip and it works fine, might be something to do with the new M1 chip?

**Comment by damithc** [comment]
Perhaps installing the missing font might help? Is that possible? e.g., is the missing font available for installing?

**Comment by kouyk** [comment]
Java should automatically find a fallback font according to my testing on Ubuntu, whereby I did remove all Windows specific fonts but the application still displays properly. This looks like an encoding issue more than font issue.

**Comment by damithc** [comment]
Thanks for the inputs so far guys. Feel free to post suggestions (if any) in that issue as well.

**Comment by damithc** [comment]
Someone fixed the problem partially by installing one missing font https://github.com/nus-cs2103-AY2122S1/forum/issues/66#issuecomment-903397511

He wants to know what other fonts are being used.

**Comment by JinHao-L** [comment]
I took a look at the font that he downloaded. Apparently, the font that he downloaded contains the `Segeo UI` font (which is used by cell_small_label). 

He needs to additionally download `Segeo UI Light` and `Segeo UI Semibold` specifically to fix the other texts (from what I see in the DarkTheme.css file)

**Comment by damithc** [comment]
Guys, shall we update AB3 to use a more common font? We can do that right now if we move fast, given the current batch hasn't started using AB3 code yet. Anyone up for submitting a PR?

**Comment by ernestlim8** [comment]
I can submit a PR, shall we use Arial as the default font?

**Comment by kouyk** [comment]
Arial does look feasible, but on Ubuntu and other open source distributions Arial is not available by default. Would it be better for us to embed an open license font like Noto instead?

Here is a list of fonts on Pop! OS 21.04 (a derivative distro from Ubuntu 21.04), see [fonts.txt](https://github.com/se-edu/addressbook-level3/files/7029943/fonts.txt)

**Comment by ernestlim8** [comment]
Seems like Noto only has Bold and Regular styles, whereas Open Sans has Light, SemiBold and Bold fonts (those that are being used by AB3). Perhaps Open Sans might be a good font to use.

**Comment by kouyk** [comment]
> Seems like Noto only has Bold and Regular styles, whereas Open Sans has Light, SemiBold and Bold fonts (those that are being used by AB3). Perhaps Open Sans might be a good font to use.

Noto Sans does have the other font weights as well. See [here](https://www.google.com/get/noto/help/cjk/).

**Comment by kouyk** [comment]
In light of the recent investigations that revealed the cause of font issues on M1 Macs, not only has this issue been resolved, the proposed fixed has also been made somewhat redundant. Nevertheless, the switch to Open Sans did make the fonts consistent across all platforms without having to rely upon the running system to select a fallback font. Should actions be taken to update the commit for the font change?

**Comment by damithc** [comment]
> Should actions be taken to update the commit for the font change?

@kouyk Do you mean, change the commit message?

**Comment by kouyk** [comment]
> @kouyk Do you mean, change the commit message?

Yes, since it does contain information that is no longer correct/relevant.

**Comment by damithc** [comment]
> Yes, since it does contain information that is no longer correct/relevant.

I guess we can, but that requires a force push -- probably should delay till this semester is over?

**Comment by kouyk** [comment]
> I guess we can, but that requires a force push -- probably should delay till this semester is over?

In this case should a new issue be opened to serve as a reminder?

**Comment by damithc** [comment]
> In this case should a new issue be opened to serve as a reminder?

Good idea @kouyk Please go ahead.
