### ISSUE TITLE
Rectifying commit message for font change

### ISSUE THREAD

**Issue by kouyk** [se-edu/addressbook-level3#110]
In 9a46153d8c43c4c3e606e364531bd3ba5a871737, the font was changed to Open Sans to workaround the font display problems when running AB3 on M1 Macs (likely under Rosetta). However, it has been later discovered that the underlying issue was likely that JavaFX libraries embedded has compatibility issues with the OpenJDK installed. The Azul build of OpenJDK 11 with JavaFX does not have such compatibility issues while also running natively on ARM, hence the primary motivation behind this change was lost.

Nevertheless, there is still significance in switching to a font like Open Sans as it helps to ensure visual consistency across all of the platforms that AB3 supports. Hence this change should be kept.

The recommendation here is to change the commit message to reflect the above mentioned rationale, replacing the less accurate descriptions that portrays the commit as a workaround rather than a meaningful fix.

**Comment by damithc** [comment]
@kouyk now that we have reverted that commit, should we leave the original commit as it is?

**Comment by kouyk** [comment]
The main motivation is to avoid any confusion should anyone come across those commits, however, with the recent revert of the PR, the commit history alone should suffice to explain the hindsight we had and clear any confusion. Thus, I do think we should leave the original commit alone.
