### ISSUE TITLE
Help needed in smoke-testing the new release

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level3#120]
@se-edu/tech-team-level1 (newly inducted members in particular) I've created a [new release](https://github.com/se-edu/addressbook-level3/releases/tag/v0.2.1.ea) with the latest changes. Please help smoke test it in your computer. Ensure you are using Java 11. If you are using Mac M1, ensure you have followed [these instructions (see advisory for Mac users)](https://nus-cs2103-ay2122s2.github.io/website/admin/programmingLanguages.html) to install the specific version of Java specified.

After testing, **please post a screenshot of the GUI in this thread**. I would like to see how it looks in various environments, given the change in concern is about fonts.

**Comment by JoelHo** [comment]
On Windows 11 Build 22000.376, Java version "11.0.11" 2021-04-20 LTS
Everything looks normal on my system. 

@damithc I think you meant to link the Java install instructions for M1 but the link is broken?

![image](https://user-images.githubusercontent.com/3416326/149268128-b00ade5e-5ae5-4209-b386-2009a250dfea.png)
![image](https://user-images.githubusercontent.com/3416326/149268151-ed80e5c3-a397-484f-af11-205f8b5036b2.png)

**Comment by damithc** [comment]
> @damithc I think you meant to link the Java install instructions for M1 but the link is broken?

Yup. Thx for the catch @JoelHo. Fixed.

**Comment by kouyk** [comment]
System: NixOS (another linux distro)
JDK: openjdk 11.0.12 2021-07-20 (with openjfx11 installed)

I do have the required fonts installed on my system so everything looks as it should.

![image](https://user-images.githubusercontent.com/1729497/149270722-d790ed6b-0408-4d32-a1e2-e283e728bc15.png)
![image](https://user-images.githubusercontent.com/1729497/149271173-00a49073-f73d-4a36-8554-b7f7173bd216.png)

**Comment by chownces** [comment]
I believe the font issue exists on certain JDKs on Intel Macs too. The Azul build works properly though.

This issue was also mentioned by a few other Intel Mac users last sem 
https://github.com/nus-cs2103-AY2122S1/forum/issues/231#issuecomment-936024007
https://github.com/nus-cs2103-AY2122S1/forum/issues/118

OS: MacOS Monterey (Intel)
### JDK: openjdk 11.0.12 (Homebrew)

<img width="733" alt="image" src="https://user-images.githubusercontent.com/53928333/149272123-5bc16f08-65e8-4354-823f-8c9da00d04bb.png">

### JDK: openjdk 11.0.13 (Azul)
<img width="734" alt="image" src="https://user-images.githubusercontent.com/53928333/149272202-76026462-1c9b-46da-90ce-70b4b54727e5.png">

<img width="553" alt="image" src="https://user-images.githubusercontent.com/53928333/149272227-ac98b6ab-b2c1-4af9-86ce-9f0eb54d2bad.png">

**Comment by JinHao-L** [comment]
System: Ubuntu 20.04 
JDK: openjdk version "11.0.13" 2021-10-19

AB3 program runs well and looks normal on Ubuntu OS

![Screenshot 2022-01-13 13:36:23](https://user-images.githubusercontent.com/52820430/149273062-1545c7c8-51a7-4732-a0dd-60e03e10503e.png)

**Comment by Tianqi-Zhu** [comment]
System: Ubuntu 18.04
JDK: openjdk 11.0.13

![image](https://user-images.githubusercontent.com/63087760/149274857-4f607309-b1f8-4d44-86ff-f54f9301465d.png)
![image](https://user-images.githubusercontent.com/63087760/149274885-f7f1c5dd-7b59-4a10-aa22-a810594e1579.png)

When I tried to resize it by dragging the left or right, there was some white flickering on the right.
When I tried to resize it by dragging the top or the bottom, there was some white flickering at the bottom.
![image](https://user-images.githubusercontent.com/63087760/149274458-3fdebc59-aaae-42db-b751-84a487cc9f59.png)

**Comment by LimJunxue** [comment]
Windows 10, java version "11.0.13" 2021-10-19 LTS
Program and functions look good to me.

![image](https://user-images.githubusercontent.com/60027105/149275981-8c444b14-7baa-4c36-bede-3f138babc47c.png)
![image](https://user-images.githubusercontent.com/60027105/149275990-9aa8ab4c-0477-45ce-94f8-36bc25214f08.png)

**Comment by vimuthm** [comment]
System: `Windows 11 Build 22471.1000`
JDK: `openjdk 11.0.9.1 2020-11-04`

Looks good!

![image](https://user-images.githubusercontent.com/62249192/149275068-d3a252ff-d6a9-4cb2-8eda-11cfe7812069.png)

For System: `Ubuntu 20.04.3 LTS` and `JDK: openjdk 11.0.11 2021-04-20`, I see no font problems but get the same flickering issue that @Tianqi-Zhu pointed out.

**Comment by eeliana** [comment]
OS: MacOS Big Sur (Intel)

Same problem as @\chownces with openjdk 11.0.12 (Homebrew) on Intel Mac.
![image](https://user-images.githubusercontent.com/62977276/149277356-5acb8417-2f43-4af2-93c2-17112f45c67b.png)

## openjdk 11.0.9.1 2020-11-04 (AdoptOpenJDK)
![image](https://user-images.githubusercontent.com/62977276/149277854-81c1dae6-267f-4023-985f-f37dea18a864.png)
![image](https://user-images.githubusercontent.com/62977276/149278142-2863e04c-6fbb-49b8-b2d9-64a031a15c07.png)

**Comment by CrownKira** [comment]
macOS version 12.0.1 (21A559), java 11.0.9 2020-10-20 LTS
All functionalities seem to work fine. no font issues or flickering issues.



    On Thursday, 13 January 2022, 02:37:00 pm GMT+8, eeliana ***@***.***> wrote:  
 
 


OS: MacOS Big Sur (Intel)

Same problem as @\chownces with openjdk 11.0.12 (Homebrew) on Intel Mac.


openjdk 11.0.9.1 2020-11-04 (AdoptOpenJDK)




—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Py0000** [comment]
Tested the functionalities and checked the fonts. Everything looks good and works on my devices!

***Test 1***
**System**: Windows 10 Home (OS Build: 18363.1556)
**Java Version**: 11.0.9 2020-10-20

![image](https://user-images.githubusercontent.com/77230044/149277464-9b693963-87a1-474e-ba4d-353cbd579bf3.png)

***Test 2***
**System**: Windows 10 Home (OS Build: 19043.1415)
**Java Version**: 11.0.10 2021-01-19

![image](https://user-images.githubusercontent.com/77230044/149279112-72a832a1-e5bd-4e8c-af52-fde1d7445d81.png)

**Comment by CrownKira** [comment]
macOS version 12.0.1 (21A559), java 11.0.9 2020-10-20 LTS

All functionalities seem to work fine. no font issues or flickering issues.

<img width="969" alt="Screenshot 2022-01-13 at 2 33 27 PM" src="https://user-images.githubusercontent.com/24221801/149279657-7433a1fb-cbb6-4be5-8311-75ead063a2a3.png">

**Comment by HolmesJJ** [comment]
## Windows 10
**System**: `Windows 10 Home 19043.1415`
**JDK**: `openjdk 11.0.9`

GUI works well (**light mode and dark mode both**), functions works well.
![image](https://user-images.githubusercontent.com/62185825/149289730-89fc3d25-bbda-48c6-a20f-992f492eab7e.png)
![image](https://user-images.githubusercontent.com/62185825/149289748-1ed95e2e-779b-4e53-b87a-9607e45b4def.png)

## macOS
**System**: `macOS Big Sur Version 11.6`
**JDK**: `openjdk 11.0.8` (AdoptOpenJDK)

GUI works well (**light mode and dark mode both**), functions works well.
![image](https://user-images.githubusercontent.com/62185825/149290001-6c0ff7f6-accd-4331-8391-15c0e96ac7a5.png)
![image](https://user-images.githubusercontent.com/62185825/149290223-d68d3d9d-3b8e-40a9-a95c-789ae25cf362.png)

**System**: `macOS Big Sur Version 11.6`
**JDK**: `openjdk 11.0.12` (Homebrew)

GUI font display error mentioned above.
![image](https://user-images.githubusercontent.com/62185825/149290700-8910d620-2908-4f12-821f-abbbd96021f4.png)
![image](https://user-images.githubusercontent.com/62185825/149290723-13dbb2cd-e3c0-40d5-ba38-3bf4b1fd194b.png)

## Ubuntu

**System**: `Ubuntu 18.04.5 LTS`
**JDK**: `javac 11.0.13`

GUI works well, functions works well.
![image](https://user-images.githubusercontent.com/62185825/149291604-3d8406c8-e1db-4a5b-a97e-1efcb84e526c.png)
![image](https://user-images.githubusercontent.com/62185825/149291636-40d104a4-561b-4df1-9884-546ddbbf7147.png)


I also reproduced the **white flickering issue** mentioned above, but **I don't think this is the application bug** since I tested other applications on my PC and all of them have the same white flickering issue.

**Comment by jayasting98** [comment]
# Ubuntu 20.04

Ubuntu 20.04.2 LTS (Running via Windows 10 WSL 2)
openjdk version "11.0.11" 2021-04-20 (OpenJDK)
Using XMing for display.

![image](https://user-images.githubusercontent.com/65202977/149292274-e445ce43-bfb9-4883-8926-3d26cb31f33d.png)

The dropdowns are strange, they are detached:
![image](https://user-images.githubusercontent.com/65202977/149292359-a30a0664-24e5-49e0-9965-9f427775fe3c.png)

The help window also does not seem work properly:
![image](https://user-images.githubusercontent.com/65202977/149292462-33230ab4-3489-47f3-9217-5d3ed0e010fd.png)

It has similar problems on resizing that @Tianqi-Zhu found.

# Windows 10

Windows 10 Build 19042.1415
java version "11.0.12" 2021-07-20 LTS (Oracle)

![image](https://user-images.githubusercontent.com/65202977/149291075-521c0fa6-84fc-47f4-89e8-539c0e90befc.png)

![image](https://user-images.githubusercontent.com/65202977/149291110-0f0c595e-264c-4e12-a62b-00520c39f0b5.png)

Looks fine overall. No problems found for Windows 10, even the resizing one.

**Comment by kingsleykuan** [comment]
# Ubuntu 18.04

System: Ubuntu 18.04.6 (with Arc-Dark theme)
Java: OpenJDK 11.0.13

Everything looks normal on my system, including the help window.

![Screenshot from 2022-01-14 12-42-43](https://user-images.githubusercontent.com/17900636/149453271-28040f80-36d1-416f-b409-5f6d086a4dda.png)

The dropdown menus are also working as intended.

![Screenshot from 2022-01-14 12-50-36](https://user-images.githubusercontent.com/17900636/149453520-d72469d3-cf99-4588-877d-f37e6a6b81ea.png)

I do notice the issue mentioned by @Tianqi-Zhu however it is a momentary flicker and not very noticeable.

**Comment by jeffsieu** [comment]
Everything looks normal. There are no flickering issues when resizing.

## System information

- Windows 11 Home 21H2, build 22000.376
- Java 11.0.12 2021-07-20 LTS

## Screenshots
![image](https://user-images.githubusercontent.com/8487294/149462780-a8208d6b-f5e2-4d0a-a8ed-76af79827fa1.png)
![image](https://user-images.githubusercontent.com/8487294/149462795-efcb37d8-3a44-464b-a510-e8c28a933c92.png)

**Comment by damithc** [comment]
Thanks everyone for reporting smoke-testing results.
@kouyk and others,
1. I guess the font problem on Mac is expected and no action needed.
2. How about the Ui anomalies reported on some Ubuntu environments? Is there a workaround?

**Comment by kouyk** [comment]
> 2. How about the Ui anomalies reported on some Ubuntu environments? Is there a workaround?

The Ui anomalies seems to be applicable to Linux based systems as a whole, as I am also able to reproduce the same issue. My findings are similar to @HolmesJJ where it is not limited to AB3, I tried out [recaf](https://github.com/Col-E/Recaf), another JavaFX application, which has a similar issue. Some quick googling seems to reveal that this is an upstream bug with JavaFX that has yet been resolved even for JavaFX 18, more details [here](https://www.mail-archive.com/openjfx-dev@openjdk.java.net/msg23675.html). If launching via CLI, it may be possible to pass the flag `-Dprism.forceUploadingPainter=true` to java and reduce the severity of the problem.

It is unlikely that we are able to find a proper resolution or workaround for this issue, furthermore this is a minor cosmetic bug that does not impact normal usage of the application.

**Comment by damithc** [comment]
> The Ui anomalies seems to be applicable to Linux based systems as a whole, as I am also able to reproduce the same issue. My findings are similar to @HolmesJJ where it is not limited to AB3, I tried out [recaf](https://github.com/Col-E/Recaf), another JavaFX application, which has a similar issue. Some quick googling seems to reveal that this is an upstream bug with JavaFX that has yet been resolved even for JavaFX 18, more details [here](https://www.mail-archive.com/openjfx-dev@openjdk.java.net/msg23675.html). If launching via CLI, it may be possible to pass the flag `-Dprism.forceUploadingPainter=true` to java and reduce the severity of the problem.
> 
> It is unlikely that we are able to find a proper resolution or workaround for this issue, furthermore this is a minor cosmetic bug that does not impact normal usage of the application.

Got it. We can leave it be. Students using the affected OS should already be familiar with the problem by the time they reach the PE, which means they will not report it as a bug of the software.

**Comment by damithc** [comment]
@se-edu/tech-team-level1 There's one student reporting that he is still facing the font problem https://github.com/nus-cs2103-AY2122S2/forum/issues/44#issuecomment-1022963388

Could you guys help follow up?

**Comment by kouyk** [comment]
> Could you guys help follow up?

Seems to be resolved, which stems from the fact that multiple versions of JDK are installed and MacOS defaulting to the highest available version when launching any jar files via the GUI. There is a [method to workaround](https://stackoverflow.com/a/44169445) that, perhaps someone on MacOS can try it out and provide a few screenshots so the advisory can be updated accordingly?

**Comment by damithc** [comment]
@se-edu/tech-team-level1 This might need your help as well https://github.com/nus-cs2103-AY2122S2/forum/issues/66

**Comment by damithc** [comment]
@se-edu/tech-team-level1 Another case https://github.com/nus-cs2103-AY2122S2/forum/issues/58#issuecomment-1025631708

Says he is not using a M1 Mac but facing a similar issue
