### ISSUE TITLE
Upgrade Checkstyle to 9.3

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [se-edu/addressbook-level3#124]
The current `build.gradle` lists `8.29` as the version for Checkstyle. However, Checkstyle 9.3 is currently the latest version available. I propose upgrading Checkstyle to it.

I have done something similar for [RepoSense](https://github.com/reposense/RepoSense/pull/1652/files#diff-5e447a4951899692f37baf49a0480288358ad0c989e745e1a8c77969529ced1f). However, some of the new checks may not be as relevant since they are for proposed new Javadoc standards within RepoSense only.

**Comment by damithc** [comment]
Thanks for proposing this @yhtMinceraft1010X We can probably tackle this over the summer when AB3 is not in active use.

**Comment by yhtMinceraft1010X** [comment]
Here are my planned changes to address this issue:
* Upgrade to [Checkstyle 10.2](https://checkstyle.sourceforge.io/releasenotes.html) which is the latest version available and also supports a minimum version of Java 11.
* Add checks that may be relevant to the [basic and intermediate Java coding standards](https://se-education.org/guides/conventions/java/intermediate.html) but are not in `checkstyle.xml`.

I noticed that Duke also has a [`checkstyle.xml` file in the `full-template` branch](https://github.com/se-edu/duke/blob/full-template/config/checkstyle/checkstyle.xml). Can I confirm if that file also needs to be updated?

**Comment by damithc** [comment]
> I noticed that Duke also has a [`checkstyle.xml` file in the `full-template` branch](https://github.com/se-edu/duke/blob/full-template/config/checkstyle/checkstyle.xml). Can I confirm if that file also needs to be updated?

@yhtMinceraft1010X Yes.
