### ISSUE TITLE
Remove legacy Travis code

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [se-edu/addressbook-level3#131]
Although we have [migrated to GitHub Actions](https://github.com/se-edu/addressbook-level3/commit/0be83b242cf13718c419d9996226b147b6cbb437), we still have [4 scripts related to Travis](https://github.com/se-edu/addressbook-level3/tree/master/config/travis). I think it should be safe to remove them since the 4 scripts have already been [ported to `.github`](https://github.com/se-edu/addressbook-level3/tree/master/.github).

**Comment by damithc** [comment]
Thanks for catching this @yhtMinceraft1010X 
Yup, go ahead and submit a PR. As this is a simple maintenance task, best to be done by a current contributor rather than leave it to a new contributor.
