### ISSUE TITLE
Rephrase 'file not found' logs shown during first run

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level3#139]
When the app is run for the first time, the log shows some 'file not found' messages that some might interpret as errors. 

![image](https://user-images.githubusercontent.com/1673303/179820561-5f56af7c-a38c-43e6-bd3b-a3f0512b08a5.png)

Suggestion: We can rephrase them to appear less like an error message.

**Comment by LimJunxue** [comment]
How's this for all 3:
`INFO: Json file ... not found, will use defaults`

**Comment by damithc** [comment]
> How's this for all 3:
> `INFO: Json file ... not found, will use defaults`

Sorry for not noticing this earlier @LimJunxue 
Yes, something along those lines sounds good. Perhaps also mention that the app deduces this is the first run and will be creating new files.
