### ISSUE TITLE
Typo on DevOps guide

### ISSUE THREAD

**Issue by ThomasHoooo** [se-edu/addressbook-level3#143]
![image](https://user-images.githubusercontent.com/78606832/190060689-44effba0-ad60-4b31-a5e9-3d3fad72b07d.png)
tests is misspelled as testes.

**Comment by damithc** [comment]
Thanks for the bug report @ThomasHoooo

**Comment by ThomasHoooo** [comment]
> Thanks for the bug report @ThomasHoooo

No problem prof!
