### ISSUE TITLE
Coding standard violation on Storage component

### ISSUE THREAD

**Issue by cheeheng** [se-edu/addressbook-level3#147]
In the file src/main/java/seedu/address/storage/JsonAdaptedPerson.java on the master directory, I found out that the variable `tagged` is not in plural even though it represents a collection of objects, hence violating CS2103T coding standard.

Below shows lines 33-47 of the code for easy reference.

```java
    /**
     * Constructs a {@code JsonAdaptedPerson} with the given person details.
     */
    @JsonCreator
    public JsonAdaptedPerson(@JsonProperty("name") String name, @JsonProperty("phone") String phone,
            @JsonProperty("email") String email, @JsonProperty("address") String address,
            @JsonProperty("tagged") List<JsonAdaptedTag> tagged) {
        this.name = name;
        this.phone = phone;
        this.email = email;
        this.address = address;
        if (tagged != null) {
            this.tagged.addAll(tagged);
        }
    }
```

Here is the relevant reference in the SE-EDU Java coding standard.
<img width="731" alt="image" src="https://user-images.githubusercontent.com/13196670/197385893-5255d900-fb27-46c6-9c6f-4b682a7b1d56.png">

**Comment by damithc** [comment]
@cheeheng Good catch. Thanks for the bug report.
