### ISSUE TITLE
Typo in `custom-styles.scss` for site website

### ISSUE THREAD

**Issue by jasonqiu212** [se-edu/addressbook-level3#149]
In `docs/_sass/minima/custom-styles.scss` line 13:

```
  order-radius : $alert-border-radius;
```

I believe this should be replaced with `border-radius`?

**Comment by damithc** [comment]
Thanks for the bug report @jasonqiu212 
Have you tried it? Does it make a difference in how the pages are displayed?

**Comment by jasonqiu212** [comment]
Hi professor, 

Yes, I observed that the border radius of the colored boxes containing tips/caution/note were affected. 

Here is a screenshot before the change:
<img width="729" alt="Screen Shot 2022-10-31 at 10 06 17 AM" src="https://user-images.githubusercontent.com/25262042/198916720-e9c8ed6d-c61d-4a84-b5c1-baad0acf392f.png">

Here is a screenshot after changing line 13 to `border-radius: $alert-border-radius`:
<img width="725" alt="Screen Shot 2022-10-31 at 10 06 33 AM" src="https://user-images.githubusercontent.com/25262042/198916726-8b5373ce-87a9-464a-82df-e2de87748359.png">

**Comment by damithc** [comment]
> Yes, I observed that the border radius of the colored boxes containing tips/caution/note were affected.
> 
> Here is a screenshot before the change: <img alt="Screen Shot 2022-10-31 at 10 06 17 AM" width="729" src="https://user-images.githubusercontent.com/25262042/198916720-e9c8ed6d-c61d-4a84-b5c1-baad0acf392f.png">
> 
> Here is a screenshot after changing line 13 to `border-radius: $alert-border-radius`: <img alt="Screen Shot 2022-10-31 at 10 06 33 AM" width="725" src="https://user-images.githubusercontent.com/25262042/198916726-8b5373ce-87a9-464a-82df-e2de87748359.png">

@jasonqiu212 Nice find. We'll fix this in due course but it will not help current users. So, feel free to share this with the classmates (e.g., post in the class forum).
