### ISSUE TITLE
Upgrade UML diagrams to the new version of PlantUML

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level3#200]
Seems the new version has some breaking changes, as the MarkBind team found (some info [here](https://github.com/MarkBind/markbind/releases/tag/v5.0.0)) e.g., no need for GraphViz on Windows

Both diagrams and Dev Guide might needs updating.

**Comment by damithc** [comment]
@Eclipse-Dominator can have a look?

**Comment by Eclipse-Dominator** [comment]
Do we adapt to the newer lighter-colored theme or should we preserve the old color scheme?

The most noticeable theme change is the border color change as well as the background change

![image](https://github.com/se-edu/addressbook-level3/assets/4567895/dc42f001-ad7d-405e-8a87-f43a15df635c)

---
For now I will use the old theme version.

**Comment by damithc** [comment]
@Eclipse-Dominator I think there is no good reason to keep the old style. We can go with the new default style.

**Comment by Eclipse-Dominator** [comment]
I think it might be better to stick with the old theme / rose theme for now as some of the color scheme changes in `style.puml` as some of the diagrams are based on the old color scheme.

**Comment by damithc** [comment]
> I think it might be better to stick with the old theme / rose theme for now as some of the color scheme changes in `style.puml` as some of the diagrams are based on the old color scheme.

I see. I would like to see the difference before making the decision. It is ideal if new batches of student's don't need to follow the legacy stuff at all, as they are unnecessary complications for them.

**Comment by Eclipse-Dominator** [comment]
I will provide a separate PR to display the changes in color schemes
