### ISSUE TITLE
DG Review

### ISSUE THREAD

**Issue by Qing-Yuan** [se-edu/addressbook-level3#30]
3.1
Not sure the difference between underlined `Components` and those not underlined.
![image](https://user-images.githubusercontent.com/39293121/78467840-aa2fe080-7743-11ea-9ed3-bc0fbe038ce2.png)
arrow tail not touching in Figure 3
3.2
does the UI execute user commands?
descriptions seem to explain how UI component interacts with other components rather than what it does itself
3.4
API point 3: "The data stored in these two list objects is reflected in UI. Therefore, any changes made to the data in these lists are shown in the UI in real-time." The first sentence doesn't exactly lead to conclusion of second sentence, in fact, both may be saying the same thing
3.5
API point 4: what is a "user-friendly version of the current `FoodRecord`"?
3.6
Not sure if its in the DG requirements but if not explicitly state that don't need elaborate, might want to describe and explain some of the common classes.
4.1
Could be just me but "lexicographical" already means there's an order aka sorted... so "Lexicographical-sorted" sounds weird to me so please verify whether the English here is correct
"lexicographic order" also sounds weird
4.1.1
Diagram does not mention sorting anywhere, what is it supposed to describe?
4.1.2
pros for alternative 2 for data structure doesn't seem to benefit the application itself
4.1.3
how does the activity diagram help to show/explain the sorting process (might be a little too high level)
4.2.1
diagram seems to be slightly different from previous command diagrams (construction of XYZCommand and running execute was previously separate, but its together in this diagram) please verify that it was really implemented this way
Step 2: does the `NomCommandParser` always create a `DailyFoodLog`?
4.2.3
What is the diagram helping to explain?
4.3.3
activity diagram doesn't show adding the food in the [else] path
4.4.1
Step 10: under what circumstances are the report not successfully generated?
4.4.2
pros and cons should be more of impact on user, impact on application (time and space) etc. rather than impact what the user does after (those we cannot control) although the effectiveness of the application can be mentioned
4.5
this "implementation" seems a bit trivial since it should have already been provided by the prof so there's nothing to really "consider" since you're using the default. would be better if you talked about the help filter thing since it was additional implementation by the team
Use Cases
try to find less straight forward use cases which might require multiple interactions with the user
Glossary
can mention its existence at the start so whoever is reading knows there's something he/she can refer to

**Comment by damithc** [comment]
Issue in the wrong place?

**Comment by Qing-Yuan** [comment]
sorry my bad
