### ISSUE TITLE
UG/DG: Omit top nav bar from PDF version

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level3#35]
Current: the top nav bar is included in the PDF version of the UG/DG.

Suggested: Although it is not a major problem, we can consider finding a way to omit it from the PDF version.

Notes: If we do that, we need to add the product name into the UG/DG page title. Perhaps we should do that either way?

**Comment by j-lum** [comment]
Think we can play around with the CSS a bit to make it omit on print.
