### ISSUE TITLE
Re-enable repo-wide checks

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level3#37]
Previously, we used Travis do to some repo-wide checks (see [here](https://github.com/nus-cs2103-AY1920S2/addressbook-level3/blob/master/docs/UsingTravis.adoc#repository-wide-checks) for more info). The scripts are given in `config/travis`. These are no longer used since we moved away from Travis.

Suggestion: add them to GitHub Actions

**Comment by j-lum** [comment]
I have a branch for this already, let me rebase and I'll make the PR.

**Comment by damithc** [comment]
> I have a branch for this already, let me rebase and I'll make the PR.

You did that already :-p. Just need the docs to be updated.

**Comment by damithc** [comment]
> Just need the docs to be updated.

Fixed by 4eafb67e0836851e0bf4e8510b66c4a529f44945
