### ISSUE TITLE
Docs: add a 'view on GitHub' link

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level3#38]
Suggestion: add a 'View on GitHub' link to the top nav bar

![image](https://user-images.githubusercontent.com/1673303/82725240-2c815d80-9d0e-11ea-84e7-4eb7448ebe0f.png)

**Comment by damithc** [comment]
@j-lum can look into this? Often, readers need a convenient way to jump from the website to the github repo.

**Comment by j-lum** [comment]
Yup I have a preview at https://j-lum.github.io/addressbook-level3/ . If it's OK then I'll make a PR.
![image](https://user-images.githubusercontent.com/22460123/88650627-79612600-d0fb-11ea-94c3-a6aa2b4e7d09.png)

**Comment by damithc** [comment]
@j-lum resize to match the size of the other menu items? alternatively, can use `On GitHub` instead of the logo.
