### ISSUE TITLE
Add back the tutorial on 'Adding a new command'

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level3#43]
[This tutorial](https://github.com/nus-cs2103-AY1920S2/addressbook-level3/blob/master/docs/tutorials/AddRemark.adoc) seem to have disappeared. Need to add it back.

**Comment by damithc** [comment]
@j-lum can do this one?

**Comment by j-lum** [comment]
That's strange I'll go take a look at it.

**Comment by damithc** [comment]
@j-lum reminder about this

**Comment by damithc** [comment]
Fixed by 86f65cc7058472c96caee9d853580af9134670c8
