### ISSUE TITLE
Site title does not follow the value in _config.yml

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level3#44]
Although the title is given as `AB-3` in the `_config.yml`, the [generated website](https://se-education.org/addressbook-level3/) doesn't seem to reflect it.

**Comment by j-lum** [comment]
That config affects the site name in the nav bar, the actual title of the index page is in `index.md`.

**Comment by damithc** [comment]
> That config affects the site name in the nav bar, the actual title of the index page is in `index.md`.

Ah, yes indeed. But the `title` in the individual pages don't seem to show up as the page title (i.e., the one shown in the browser tab) either.
![image](https://user-images.githubusercontent.com/1673303/84752857-e491e580-aff0-11ea-8fa7-da672608494e.png)
