### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by aizatazhar** [se-edu/addressbook-level3#52]
In AB3's [CommitActivityDiagram](https://github.com/se-edu/addressbook-level3/blob/master/docs/images/CommitActivityDiagram.png), `Purge redunant states` should be `Purge redundant states`

In AB3's [Add Remark Tutorial](https://github.com/se-edu/addressbook-level3/blob/master/docs/tutorials/AddRemark.md) `throw an CommandException` should be `throw a CommandException`, and `Remark has no constrains` should be `Remark has no constraints`

**Comment by damithc** [comment]
Thanks for the bug report @aizatazhar
