### ISSUE TITLE
Allows editing a contact to become a duplicate of another

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level3#57]
Reported in a student project but it seems the bug originates in AB3:
https://github.com/nus-cs2103-AY2021S1/pe-dev-response/issues/5266
https://github.com/nus-cs2103-AY2021S1/pe-dev-response/issues/5288

Steps to reproduce:
1. edit 1 n/Bernice Yu
2. edit 1 p/99272758
3. edit 1 e/berniceyu@example.com
4. edit 1 t/colleagues t/friends
5. edit 1 a/Blk 30 Lorong 3 Serangoon Gardens, #07-18

**Result:** 
The app allowed duplicate contacts
![image](https://user-images.githubusercontent.com/20136490/99362243-33b8ab00-28ee-11eb-9a1e-34bc27efa45b.png)

Also, when we closed and reopen the app, the app started empty (because the data file had been corrupted by duplicate contacts)

![image](https://user-images.githubusercontent.com/20136490/99362897-05879b00-28ef-11eb-9395-144e0c0bd69a.png)

**Comment by pyokagan** [comment]
I vaguely recall saying some stuff about this before.

Did a google search, and found this: https://gitter.im/se-edu/Lobby?at=5c7651758a7def0752e405af , discussion might be useful to others.

**Comment by damithc** [comment]
> I vaguely recall saying some stuff about this before.
> 
> Did a google search, and found this: https://gitter.im/se-edu/Lobby?at=5c7651758a7def0752e405af , discussion might be useful to others.

Good memory! Thanks for the reference @pyokagan
