### ISSUE TITLE
Page breaks cut through content when converted to PDF

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level3#59]
![image](https://user-images.githubusercontent.com/1673303/99906540-a4a6fb00-2d12-11eb-9fca-c79e29897ff5.png)

MarkBind doesn't seem to have this problem. A Jekyll-specific problem?

**Comment by j-lum** [comment]
https://talk.jekyllrb.com/t/how-to-make-online-pages-that-also-print-nicely-as-pdf/3646/10

There's a bit of discussion here, Prince gets mentioned a lot but as much as possible we would want to avoid using proprietary tools.

**Comment by damithc** [comment]
> https://talk.jekyllrb.com/t/how-to-make-online-pages-that-also-print-nicely-as-pdf/3646/10
> 
> There's a bit of discussion here, Prince gets mentioned a lot but as much as possible we would want to avoid using proprietary tools.

Not sure if it's the same problem. In our case the page break goes right through contents (a single character/image split into two pages). I don't mind a page break splitting a paragraph in the middle but splitting a single line into two pages is unreasonable.

**Comment by j-lum** [comment]
Hmm, I think I figured out some CSS to solve most of the issues, are there any sample DG for me to test them on? The default DG only has one break in a hint box.

**Comment by damithc** [comment]
Thanks @j-lum 
Perhaps try adding some extra blank lines to move an image/paragraphs/table into a page break location? Would that work?

**Comment by damithc** [comment]
@j-lum any updates?

**Comment by RuiFengg** [comment]
I remember my team inspected the page to manually add page breaks at places that were getting cut off. Which is the file that is responsible for the printed page view? There are some solutions on SO suggesting adding `break inside: avoid` to the media print query

**Comment by damithc** [comment]
> I remember my team inspected the page to manually add page breaks at places that were getting cut off.

That's the extra work we are trying to avoid. There must be a way to solve it because a similar problem doesn't happen in the cs2103 website (which uses a different tool to build the website).

**Comment by RuiFengg** [comment]
After applying the `break inside: avoid` code for my team's UG. It seemed to have cleaned up the print preview by removing all the single line text cuts correctly.

How should I go about testing it on a branch from the fork since github pages and CI only reflects the changes on the original base master?

**Comment by damithc** [comment]
> After applying the break inside: avoid code for my team's UG. It seemed to have cleaned up the print preview by removing all the single line text cuts correctly.

Good to hear that

> How should I go about testing it on a branch from the fork since github pages and CI only reflects the changes on the original base master?

You can install Jekyll locally and preview the site locally. https://se-education.org/guides/tutorials/jekyll.html#updating-documents
