### ISSUE TITLE
UG: mention security setting in case of using Mac

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level3#62]
Double-clicking the jar file might not work in Mac computers.

Suggested: mention how to overcome it in the UG

**Comment by francisyzy** [comment]
Related issue from nus-cs2103-AY2223S2/forum
https://github.com/nus-cs2103-AY2223S2/forum/issues/188

I think this issue can be closed as the use of CLI to open the jar file is required. https://github.com/se-edu/addressbook-level3/issues/140#issuecomment-1593376613

**Comment by damithc** [comment]
Thanks @francisyzy
