### ISSUE TITLE
Unnecessary call to super() in StorageManager.java

### ISSUE THREAD

**Issue by tlylt** [se-edu/addressbook-level3#83]
Hello, the call `super()` within the `StorageManager` class (line 23 -30) seems to be meaningless and could be removed to avoid misunderstanding:
```java
    /**
     * Creates a {@code StorageManager} with the given {@code AddressBookStorage} and {@code UserPrefStorage}.
     */
    public StorageManager(AddressBookStorage addressBookStorage, UserPrefsStorage userPrefsStorage) {
        super();
        this.addressBookStorage = addressBookStorage;
        this.userPrefsStorage = userPrefsStorage;
    }
```
Discussion on this minor issue can be found [here](https://github.com/nus-cs2103-AY2021S2/forum/issues/181).
Thank you.

**Comment by damithc** [comment]
Might apply to other similar classes as well. I noticed the same problem in at least one other class.
