### ISSUE TITLE
Missing association from LogicManager to Storage in Logic class diagram

### ISSUE THREAD

**Issue by w2vgd** [se-edu/addressbook-level3#84]
Hi, as per the code from the `LogicManager` class, there should be an association from `LogicManager` to `Storage` in the class diagram for the `Logic` component.
```
public class LogicManager implements Logic {
    private final Model model;
    private final Storage storage;
    private final AddressBookParser addressBookParser;
    ...
}
```

However, the current class diagram is missing this association:
![image](https://user-images.githubusercontent.com/65358857/112352326-a1923a80-8d05-11eb-8a2e-07ee51a046da.png)

**Comment by damithc** [comment]
Thanks for the bug report @w2vgd
